replicaCount: 1

image:
  repository: lexodat2111/mlpgan-api
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  path: /health
  port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
