name: train and deploy MLPGAN API

on:
  push: # trigger on push to main branch 
    branches:
      - main

jobs:
  train-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=lexodat2111/mlpgan-api:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: update deployment yaml
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/# last-updated:.*/# last-updated: $TIMESTAMP/" argo_conf/deployment.yaml || echo "# last-updated: $TIMESTAMP" >> argo_conf/deployment.yaml
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add argo_conf/deployment.yaml
          git commit -m "Trigger ArgoCD deploy at $TIMESTAMP"
          git push

